name: Feature Request
description: Suggest a new feature
title: "[Feature]: "
labels:
  - enhancement

body:
  - type: textarea
    id: feature
    attributes:
      label: Feature Description
      description: Describe the feature you'd like to see.
    validations:
      required: true

  - type: textarea
    id: benefit
    attributes:
      label: Why is this useful?